/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 997542b59aa2a9bee79820e56d4d2ee2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database";
	}
	interface Env {
		TOWER_API_BASE_URL: "https://placeholder.api.tower-delight.local";
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TOWER_API_BASE_URL">> {}
}
