/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: c95356be32a9da399631fb5b5eca8341)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		TOWER_API_BASE_URL: "https://placeholder.api.tower-delight.local";
		ASSETS: Fetcher;
		DATABASE: DurableObjectNamespace;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TOWER_API_BASE_URL">> {}
}
